providers:
  openai:
    models:
      default: gpt-4o-mini
      grader: gpt-4o-mini

  anthropic:
    models:
      default: claude-3-haiku-20240307
      grader: claude-3-sonnet-20241022

  openrouter:
    base_url: https://openrouter.ai/api/v1
    models:
      default: meta-llama/llama-3.1-8b-instruct
      grader: meta-llama/llama-3.1-8b-instruct

prompts:
  active: "confidence"  # Может быть: "none", "confidence", "custom" задается в prompts/templates.py
  custom_text: null  # Your custom prompt template if you don't want use null