providers:
  openai:
    models:
      default: gpt-4o-mini
      grader: gpt-4o

  anthropic:
    models:
      default: claude-3-haiku-20240307
      grader: claude-3-sonnet-20241022

  openrouter:
    base_url: https://openrouter.ai/api/v1
    models:
      default: qwen/qwen1.5-72b
