providers:
  openai:
    models:
      default: gpt-4o-mini
      grader: gpt-4o-mini

  anthropic:
    models:
      default: claude-3-haiku-20240307
      grader: claude-3-sonnet-20241022

  openrouter:
    base_url: https://openrouter.ai/api/v1
    models:
      default: qwen/qwen1.5-72b

prompts:
  active: "confidence"  # Может быть: "none", "confidence", "custom"
  custom_text: none  # Если нужен свой промпт, указываем его здесь